version: "2"
services:
  lpcweb:
     image: debian:jessie
     label: "{{branchName}}-lpcweb"
     ports:
       - "8000"
     command: ['python', '-m', 'SimpleHTTPServer']
     dev_overrides:
       environment:
         - "HOST=0.0.0.0"

