version: "2"
services:
  lpcweb:
     image: debian:jessie
     labels: ["{{BRANCH_NAME}}-simple"]
     ports:
       - "8000"
     command: ['python', '-m', 'SimpleHTTPServer']
     dev_overrides:
       environment:
         - "HOST=0.0.0.0"

