version: "2"
services:
  {{BRANCH_NAME}}:
     image: debian:jessie
     labels: ["lpc-web-{{BRANCH_NAME}}"]
     ports:
       - "8000"
     command: ['python', '-m', 'SimpleHTTPServer']
     dev_overrides:
       environment:
         - "HOST=0.0.0.0"

