version: "2"
services:
  web:
     image: debian:jessie
     ports:
       - "8005:8000"
     command: ['python', '-m', 'SimpleHTTPServer']
     dev_overrides:
       environment:
         - "HOST=0.0.0.0"

